(in-package #:rpd-boardgame)

(defclass hex-cell (cell) ())

(defmethod neighbor-cells ((self hex-cell))
  (with-coords (row column self)
    `((,(1+ row) ,column)
      (,row ,(1+ column))
      (,(1- row) ,column)
      (,row ,(1- column))
      (,(1+ row) ,(1- column))
      (,(1- row) ,(1+ column)))))

(defmethod vertices ((cell hex-cell))
  (with-coords (row column cell)
    `(#(,row ,column :l)
       #(,row ,column :r)
       #(,(1+ row) ,column :l)
       #(,(1+ row) ,(1- column) :l)
       #(,(1- row) ,column :r)
       #(,(1- row) ,(1+ column) :r))))
